#!/usr/bin/bash

if [ -z "$1" ]; then
 echo "Error: No bucket name provided"
 exit 1
fi

BUCKET_NAME=$1

REGION="ca-central-1"

aws s3api create-bucket --bucket "$BUCKET_NAME" \
 --create-bucket-configuration="LocationConstraint=$REGION"

if [ $? -eq 0 ]; then
 echo "Bucket $BUCKET_NAME created successfully in region $REGION."
else
 echo "Failed to create bucket $BUCKET_NAME in region $REGION"
 exit 1
fi

